#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("RadaeePDFDemo.Resource", IsApplication=true)]

namespace RadaeePDFDemo
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010007
			public const int font = 2130771975;
			
			// aapt resource value: 0x7f010000
			public const int fontProviderAuthority = 2130771968;
			
			// aapt resource value: 0x7f010003
			public const int fontProviderCerts = 2130771971;
			
			// aapt resource value: 0x7f010004
			public const int fontProviderFetchStrategy = 2130771972;
			
			// aapt resource value: 0x7f010005
			public const int fontProviderFetchTimeout = 2130771973;
			
			// aapt resource value: 0x7f010001
			public const int fontProviderPackage = 2130771969;
			
			// aapt resource value: 0x7f010002
			public const int fontProviderQuery = 2130771970;
			
			// aapt resource value: 0x7f010006
			public const int fontStyle = 2130771974;
			
			// aapt resource value: 0x7f010008
			public const int fontWeight = 2130771976;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Boolean
		{
			
			// aapt resource value: 0x7f060000
			public const int abc_action_bar_embed_tabs = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int landscape_only = 2131099649;
			
			static Boolean()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Boolean()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f080000
			public const int notification_action_color_filter = 2131230720;
			
			// aapt resource value: 0x7f080001
			public const int notification_icon_bg_color = 2131230721;
			
			// aapt resource value: 0x7f080002
			public const int ripple_material_light = 2131230722;
			
			// aapt resource value: 0x7f080003
			public const int secondary_text_default_material_light = 2131230723;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f070004
			public const int compat_button_inset_horizontal_material = 2131165188;
			
			// aapt resource value: 0x7f070005
			public const int compat_button_inset_vertical_material = 2131165189;
			
			// aapt resource value: 0x7f070006
			public const int compat_button_padding_horizontal_material = 2131165190;
			
			// aapt resource value: 0x7f070007
			public const int compat_button_padding_vertical_material = 2131165191;
			
			// aapt resource value: 0x7f070008
			public const int compat_control_corner_material = 2131165192;
			
			// aapt resource value: 0x7f070009
			public const int notification_action_icon_size = 2131165193;
			
			// aapt resource value: 0x7f07000a
			public const int notification_action_text_size = 2131165194;
			
			// aapt resource value: 0x7f07000b
			public const int notification_big_circle_margin = 2131165195;
			
			// aapt resource value: 0x7f070001
			public const int notification_content_margin_start = 2131165185;
			
			// aapt resource value: 0x7f07000c
			public const int notification_large_icon_height = 2131165196;
			
			// aapt resource value: 0x7f07000d
			public const int notification_large_icon_width = 2131165197;
			
			// aapt resource value: 0x7f070002
			public const int notification_main_column_padding_top = 2131165186;
			
			// aapt resource value: 0x7f070003
			public const int notification_media_narrow_margin = 2131165187;
			
			// aapt resource value: 0x7f07000e
			public const int notification_right_icon_size = 2131165198;
			
			// aapt resource value: 0x7f070000
			public const int notification_right_side_padding_top = 2131165184;
			
			// aapt resource value: 0x7f07000f
			public const int notification_small_icon_background_padding = 2131165199;
			
			// aapt resource value: 0x7f070010
			public const int notification_small_icon_size_as_large = 2131165200;
			
			// aapt resource value: 0x7f070011
			public const int notification_subtext_size = 2131165201;
			
			// aapt resource value: 0x7f070012
			public const int notification_top_pad = 2131165202;
			
			// aapt resource value: 0x7f070013
			public const int notification_top_pad_large_text = 2131165203;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int bar_back = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int btn_annot_ellipse = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int btn_annot_ink = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int btn_annot_line = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int btn_annot_note = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int btn_annot_rect = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int btn_back = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int btn_cancel = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int btn_done = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int btn_ink = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int btn_left = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int btn_outline = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int btn_perform = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int btn_print = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int btn_redo = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int btn_remove = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int btn_right = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int btn_search = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int btn_select = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int btn_undo = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int btn_view = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int btn_view_dual = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int btn_view_horz = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int btn_view_single = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int btn_view_vert = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int file03 = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int folder0 = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int folder1 = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int folder2 = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public const int ic_add = 2130837533;
			
			// aapt resource value: 0x7f02001e
			public const int ic_bookmarks = 2130837534;
			
			// aapt resource value: 0x7f02001f
			public const int ic_more = 2130837535;
			
			// aapt resource value: 0x7f020020
			public const int Icon = 2130837536;
			
			// aapt resource value: 0x7f020021
			public const int menu_back = 2130837537;
			
			// aapt resource value: 0x7f020022
			public const int notification_action_background = 2130837538;
			
			// aapt resource value: 0x7f020023
			public const int notification_bg = 2130837539;
			
			// aapt resource value: 0x7f020024
			public const int notification_bg_low = 2130837540;
			
			// aapt resource value: 0x7f020025
			public const int notification_bg_low_normal = 2130837541;
			
			// aapt resource value: 0x7f020026
			public const int notification_bg_low_pressed = 2130837542;
			
			// aapt resource value: 0x7f020027
			public const int notification_bg_normal = 2130837543;
			
			// aapt resource value: 0x7f020028
			public const int notification_bg_normal_pressed = 2130837544;
			
			// aapt resource value: 0x7f020029
			public const int notification_icon_background = 2130837545;
			
			// aapt resource value: 0x7f020030
			public const int notification_template_icon_bg = 2130837552;
			
			// aapt resource value: 0x7f020031
			public const int notification_template_icon_low_bg = 2130837553;
			
			// aapt resource value: 0x7f02002a
			public const int notification_tile_bg = 2130837546;
			
			// aapt resource value: 0x7f02002b
			public const int notify_panel_notification_icon_bg = 2130837547;
			
			// aapt resource value: 0x7f02002c
			public const int pdf_custom_stamp = 2130837548;
			
			// aapt resource value: 0x7f02002d
			public const int pt_end = 2130837549;
			
			// aapt resource value: 0x7f02002e
			public const int pt_start = 2130837550;
			
			// aapt resource value: 0x7f02002f
			public const int save = 2130837551;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f0a0038
			public const int action_container = 2131361848;
			
			// aapt resource value: 0x7f0a0044
			public const int action_divider = 2131361860;
			
			// aapt resource value: 0x7f0a0039
			public const int action_image = 2131361849;
			
			// aapt resource value: 0x7f0a003a
			public const int action_text = 2131361850;
			
			// aapt resource value: 0x7f0a0045
			public const int actions = 2131361861;
			
			// aapt resource value: 0x7f0a0034
			public const int activate = 2131361844;
			
			// aapt resource value: 0x7f0a0050
			public const int add_bookmark = 2131361872;
			
			// aapt resource value: 0x7f0a0051
			public const int add_bookmark_icon = 2131361873;
			
			// aapt resource value: 0x7f0a004d
			public const int annot_combo = 2131361869;
			
			// aapt resource value: 0x7f0a004f
			public const int annot_text = 2131361871;
			
			// aapt resource value: 0x7f0a0005
			public const int async = 2131361797;
			
			// aapt resource value: 0x7f0a0006
			public const int blocking = 2131361798;
			
			// aapt resource value: 0x7f0a0016
			public const int btn_annot = 2131361814;
			
			// aapt resource value: 0x7f0a0012
			public const int btn_annot_ink = 2131361810;
			
			// aapt resource value: 0x7f0a000f
			public const int btn_annot_line = 2131361807;
			
			// aapt resource value: 0x7f0a0013
			public const int btn_annot_note = 2131361811;
			
			// aapt resource value: 0x7f0a0011
			public const int btn_annot_oval = 2131361809;
			
			// aapt resource value: 0x7f0a000e
			public const int btn_annot_rect = 2131361806;
			
			// aapt resource value: 0x7f0a0010
			public const int btn_annot_stamp = 2131361808;
			
			// aapt resource value: 0x7f0a000a
			public const int btn_back = 2131361802;
			
			// aapt resource value: 0x7f0a000b
			public const int btn_edit = 2131361803;
			
			// aapt resource value: 0x7f0a0015
			public const int btn_find = 2131361813;
			
			// aapt resource value: 0x7f0a0033
			public const int btn_goto = 2131361843;
			
			// aapt resource value: 0x7f0a001d
			public const int btn_left = 2131361821;
			
			// aapt resource value: 0x7f0a001b
			public const int btn_more = 2131361819;
			
			// aapt resource value: 0x7f0a0018
			public const int btn_outline = 2131361816;
			
			// aapt resource value: 0x7f0a000c
			public const int btn_perform = 2131361804;
			
			// aapt resource value: 0x7f0a001a
			public const int btn_redo = 2131361818;
			
			// aapt resource value: 0x7f0a000d
			public const int btn_remove = 2131361805;
			
			// aapt resource value: 0x7f0a001c
			public const int btn_right = 2131361820;
			
			// aapt resource value: 0x7f0a0017
			public const int btn_select = 2131361815;
			
			// aapt resource value: 0x7f0a0019
			public const int btn_undo = 2131361817;
			
			// aapt resource value: 0x7f0a0014
			public const int btn_view = 2131361812;
			
			// aapt resource value: 0x7f0a0060
			public const int buttons_container = 2131361888;
			
			// aapt resource value: 0x7f0a002b
			public const int chk_show = 2131361835;
			
			// aapt resource value: 0x7f0a0043
			public const int chronometer = 2131361859;
			
			// aapt resource value: 0x7f0a0064
			public const int clear_button = 2131361892;
			
			// aapt resource value: 0x7f0a0047
			public const int curl_view = 2131361863;
			
			// aapt resource value: 0x7f0a0021
			public const int delete = 2131361825;
			
			// aapt resource value: 0x7f0a0029
			public const int dlg_input = 2131361833;
			
			// aapt resource value: 0x7f0a0023
			public const int dlg_show_note = 2131361827;
			
			// aapt resource value: 0x7f0a0007
			public const int forever = 2131361799;
			
			// aapt resource value: 0x7f0a005b
			public const int horz = 2131361883;
			
			// aapt resource value: 0x7f0a003c
			public const int icon = 2131361852;
			
			// aapt resource value: 0x7f0a0046
			public const int icon_group = 2131361862;
			
			// aapt resource value: 0x7f0a0059
			public const int imageView1 = 2131361881;
			
			// aapt resource value: 0x7f0a005d
			public const int imageView2 = 2131361885;
			
			// aapt resource value: 0x7f0a005f
			public const int imageView3 = 2131361887;
			
			// aapt resource value: 0x7f0a003f
			public const int info = 2131361855;
			
			// aapt resource value: 0x7f0a0008
			public const int italic = 2131361800;
			
			// aapt resource value: 0x7f0a0026
			public const int lab_content = 2131361830;
			
			// aapt resource value: 0x7f0a0020
			public const int lab_page = 2131361824;
			
			// aapt resource value: 0x7f0a0024
			public const int lab_subj = 2131361828;
			
			// aapt resource value: 0x7f0a0022
			public const int label = 2131361826;
			
			// aapt resource value: 0x7f0a004e
			public const int lay_root = 2131361870;
			
			// aapt resource value: 0x7f0a0000
			public const int line1 = 2131361792;
			
			// aapt resource value: 0x7f0a0001
			public const int line3 = 2131361793;
			
			// aapt resource value: 0x7f0a0028
			public const int lst_outline = 2131361832;
			
			// aapt resource value: 0x7f0a0009
			public const int normal = 2131361801;
			
			// aapt resource value: 0x7f0a0041
			public const int notification_background = 2131361857;
			
			// aapt resource value: 0x7f0a003d
			public const int notification_main_column = 2131361853;
			
			// aapt resource value: 0x7f0a003b
			public const int notification_main_column_container = 2131361851;
			
			// aapt resource value: 0x7f0a0035
			public const int open = 2131361845;
			
			// aapt resource value: 0x7f0a0037
			public const int open_assets = 2131361847;
			
			// aapt resource value: 0x7f0a0036
			public const int open_http = 2131361846;
			
			// aapt resource value: 0x7f0a004c
			public const int pdf_nav = 2131361868;
			
			// aapt resource value: 0x7f0a0048
			public const int pdf_pager = 2131361864;
			
			// aapt resource value: 0x7f0a0049
			public const int pdf_view = 2131361865;
			
			// aapt resource value: 0x7f0a0056
			public const int print = 2131361878;
			
			// aapt resource value: 0x7f0a0057
			public const int print_icon = 2131361879;
			
			// aapt resource value: 0x7f0a004a
			public const int progress = 2131361866;
			
			// aapt resource value: 0x7f0a002d
			public const int rad_copy = 2131361837;
			
			// aapt resource value: 0x7f0a002c
			public const int rad_group = 2131361836;
			
			// aapt resource value: 0x7f0a002e
			public const int rad_highlight = 2131361838;
			
			// aapt resource value: 0x7f0a0031
			public const int rad_squiggly = 2131361841;
			
			// aapt resource value: 0x7f0a0030
			public const int rad_strikeout = 2131361840;
			
			// aapt resource value: 0x7f0a002f
			public const int rad_underline = 2131361839;
			
			// aapt resource value: 0x7f0a0040
			public const int right_icon = 2131361856;
			
			// aapt resource value: 0x7f0a003e
			public const int right_side = 2131361854;
			
			// aapt resource value: 0x7f0a0054
			public const int save = 2131361876;
			
			// aapt resource value: 0x7f0a0065
			public const int save_button = 2131361893;
			
			// aapt resource value: 0x7f0a0055
			public const int save_icon = 2131361877;
			
			// aapt resource value: 0x7f0a001f
			public const int seek_page = 2131361823;
			
			// aapt resource value: 0x7f0a0052
			public const int show_bookmarks = 2131361874;
			
			// aapt resource value: 0x7f0a0053
			public const int show_bookmarks_icon = 2131361875;
			
			// aapt resource value: 0x7f0a0063
			public const int signature_pad = 2131361891;
			
			// aapt resource value: 0x7f0a0061
			public const int signature_pad_container = 2131361889;
			
			// aapt resource value: 0x7f0a0062
			public const int signature_pad_description = 2131361890;
			
			// aapt resource value: 0x7f0a0002
			public const int text = 2131361794;
			
			// aapt resource value: 0x7f0a0003
			public const int text2 = 2131361795;
			
			// aapt resource value: 0x7f0a0066
			public const int thumb_view = 2131361894;
			
			// aapt resource value: 0x7f0a0042
			public const int time = 2131361858;
			
			// aapt resource value: 0x7f0a0004
			public const int title = 2131361796;
			
			// aapt resource value: 0x7f0a0027
			public const int txt_content = 2131361831;
			
			// aapt resource value: 0x7f0a001e
			public const int txt_find = 2131361822;
			
			// aapt resource value: 0x7f0a0032
			public const int txt_name = 2131361842;
			
			// aapt resource value: 0x7f0a002a
			public const int txt_password = 2131361834;
			
			// aapt resource value: 0x7f0a004b
			public const int txt_path = 2131361867;
			
			// aapt resource value: 0x7f0a0025
			public const int txt_subj = 2131361829;
			
			// aapt resource value: 0x7f0a005e
			public const int view_dual = 2131361886;
			
			// aapt resource value: 0x7f0a005a
			public const int view_horz = 2131361882;
			
			// aapt resource value: 0x7f0a005c
			public const int view_single = 2131361884;
			
			// aapt resource value: 0x7f0a0058
			public const int view_vert = 2131361880;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Integer
		{
			
			// aapt resource value: 0x7f0b0000
			public const int status_bar_notification_info_maxnum = 2131427328;
			
			static Integer()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Integer()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int bar_act = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int bar_annot = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int bar_cmd = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int bar_find = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int bar_seek = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int bookmark_popup_menu = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int bookmark_row = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int dlg_note = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int dlg_outline = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int dlg_pswd = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int dlg_text = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int item_outline = 2130903051;
			
			// aapt resource value: 0x7f03000c
			public const int Main = 2130903052;
			
			// aapt resource value: 0x7f03000d
			public const int notification_action = 2130903053;
			
			// aapt resource value: 0x7f03000e
			public const int notification_action_tombstone = 2130903054;
			
			// aapt resource value: 0x7f03000f
			public const int notification_template_custom_big = 2130903055;
			
			// aapt resource value: 0x7f030010
			public const int notification_template_icon_group = 2130903056;
			
			// aapt resource value: 0x7f030011
			public const int notification_template_part_chronometer = 2130903057;
			
			// aapt resource value: 0x7f030012
			public const int notification_template_part_time = 2130903058;
			
			// aapt resource value: 0x7f030013
			public const int pdf_curl = 2130903059;
			
			// aapt resource value: 0x7f030014
			public const int pdf_fragment = 2130903060;
			
			// aapt resource value: 0x7f030015
			public const int pdf_layout = 2130903061;
			
			// aapt resource value: 0x7f030016
			public const int pdf_nav = 2130903062;
			
			// aapt resource value: 0x7f030017
			public const int pop_combo = 2130903063;
			
			// aapt resource value: 0x7f030018
			public const int pop_edit = 2130903064;
			
			// aapt resource value: 0x7f030019
			public const int pop_more = 2130903065;
			
			// aapt resource value: 0x7f03001a
			public const int pop_view = 2130903066;
			
			// aapt resource value: 0x7f03001b
			public const int signature_pad = 2130903067;
			
			// aapt resource value: 0x7f03001c
			public const int thumb_view = 2130903068;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Raw
		{
			
			// aapt resource value: 0x7f040000
			public const int amiri_regular = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int arimo = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int arimob = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int arimobi = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int arimoi = 2130968580;
			
			// aapt resource value: 0x7f040005
			public const int cmaps = 2130968581;
			
			// aapt resource value: 0x7f040006
			public const int cmyk_rgb = 2130968582;
			
			// aapt resource value: 0x7f040007
			public const int cousine = 2130968583;
			
			// aapt resource value: 0x7f040008
			public const int cousineb = 2130968584;
			
			// aapt resource value: 0x7f040009
			public const int cousinebi = 2130968585;
			
			// aapt resource value: 0x7f04000a
			public const int cousinei = 2130968586;
			
			// aapt resource value: 0x7f04000b
			public const int rdf013 = 2130968587;
			
			// aapt resource value: 0x7f04000c
			public const int symbol = 2130968588;
			
			// aapt resource value: 0x7f04000d
			public const int tinos = 2130968589;
			
			// aapt resource value: 0x7f04000e
			public const int tinosb = 2130968590;
			
			// aapt resource value: 0x7f04000f
			public const int tinosbi = 2130968591;
			
			// aapt resource value: 0x7f040010
			public const int tinosi = 2130968592;
			
			// aapt resource value: 0x7f040011
			public const int umaps = 2130968593;
			
			static Raw()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Raw()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050052
			public const int ApplicationName = 2131034194;
			
			// aapt resource value: 0x7f050051
			public const int Hello = 2131034193;
			
			// aapt resource value: 0x7f050001
			public const int about = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int advance = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int annotation_failed = 2131034115;
			
			// aapt resource value: 0x7f050004
			public const int app_name = 2131034116;
			
			// aapt resource value: 0x7f050046
			public const int bookmark_add = 2131034182;
			
			// aapt resource value: 0x7f050047
			public const int bookmark_already_added = 2131034183;
			
			// aapt resource value: 0x7f050048
			public const int bookmark_error = 2131034184;
			
			// aapt resource value: 0x7f050049
			public const int bookmark_label = 2131034185;
			
			// aapt resource value: 0x7f05004a
			public const int bookmark_remove_error = 2131034186;
			
			// aapt resource value: 0x7f05004b
			public const int bookmark_show = 2131034187;
			
			// aapt resource value: 0x7f05004c
			public const int bookmark_success = 2131034188;
			
			// aapt resource value: 0x7f05004d
			public const int bookmarks = 2131034189;
			
			// aapt resource value: 0x7f050005
			public const int browse_open_file = 2131034117;
			
			// aapt resource value: 0x7f050006
			public const int cancel = 2131034118;
			
			// aapt resource value: 0x7f050007
			public const int cannot_write_or_encrypted = 2131034119;
			
			// aapt resource value: 0x7f050008
			public const int catalog_not_found = 2131034120;
			
			// aapt resource value: 0x7f05003f
			public const int clear = 2131034175;
			
			// aapt resource value: 0x7f050040
			public const int confirm = 2131034176;
			
			// aapt resource value: 0x7f050009
			public const int copy_text = 2131034121;
			
			// aapt resource value: 0x7f05000a
			public const int copy_text_to_clipboard = 2131034122;
			
			// aapt resource value: 0x7f05000b
			public const int create_pdf = 2131034123;
			
			// aapt resource value: 0x7f05000c
			public const int curl_pages = 2131034124;
			
			// aapt resource value: 0x7f050041
			public const int delete = 2131034177;
			
			// aapt resource value: 0x7f050042
			public const int delete_signature_message = 2131034178;
			
			// aapt resource value: 0x7f05000d
			public const int dual_page = 2131034125;
			
			// aapt resource value: 0x7f05000e
			public const int edit_catalog_failed = 2131034126;
			
			// aapt resource value: 0x7f05000f
			public const int exiting = 2131034127;
			
			// aapt resource value: 0x7f050010
			public const int failed_encryption = 2131034128;
			
			// aapt resource value: 0x7f050011
			public const int failed_invalid_format = 2131034129;
			
			// aapt resource value: 0x7f050012
			public const int failed_invalid_password = 2131034130;
			
			// aapt resource value: 0x7f050013
			public const int failed_invalid_path = 2131034131;
			
			// aapt resource value: 0x7f050014
			public const int failed_unknown = 2131034132;
			
			// aapt resource value: 0x7f050015
			public const int file_not_exist = 2131034133;
			
			// aapt resource value: 0x7f050016
			public const int file_not_exist_error = 2131034134;
			
			// aapt resource value: 0x7f050017
			public const int file_not_opened = 2131034135;
			
			// aapt resource value: 0x7f050018
			public const int highlight_texts = 2131034136;
			
			// aapt resource value: 0x7f050019
			public const int horizontal = 2131034137;
			
			// aapt resource value: 0x7f05001a
			public const int input_password = 2131034138;
			
			// aapt resource value: 0x7f05001b
			public const int javascript = 2131034139;
			
			// aapt resource value: 0x7f05004e
			public const int loading = 2131034190;
			
			// aapt resource value: 0x7f05001c
			public const int loading_pdf = 2131034140;
			
			// aapt resource value: 0x7f05001d
			public const int no = 2131034141;
			
			// aapt resource value: 0x7f05004f
			public const int no_bookmarks = 2131034191;
			
			// aapt resource value: 0x7f05001e
			public const int no_more_found = 2131034142;
			
			// aapt resource value: 0x7f05001f
			public const int no_more_redo = 2131034143;
			
			// aapt resource value: 0x7f050020
			public const int no_more_undo = 2131034144;
			
			// aapt resource value: 0x7f050021
			public const int no_pdf_outlines = 2131034145;
			
			// aapt resource value: 0x7f050022
			public const int note_content = 2131034146;
			
			// aapt resource value: 0x7f050023
			public const int ok = 2131034147;
			
			// aapt resource value: 0x7f050024
			public const int open_asset = 2131034148;
			
			// aapt resource value: 0x7f050025
			public const int open_http = 2131034149;
			
			// aapt resource value: 0x7f050026
			public const int open_sdcard = 2131034150;
			
			// aapt resource value: 0x7f050027
			public const int page_change_block = 2131034151;
			
			// aapt resource value: 0x7f050028
			public const int pdf_outline = 2131034152;
			
			// aapt resource value: 0x7f050029
			public const int pdf_print_calculation_failed = 2131034153;
			
			// aapt resource value: 0x7f05002a
			public const int pdf_print_not_available = 2131034154;
			
			// aapt resource value: 0x7f05002b
			public const int please_wait = 2131034155;
			
			// aapt resource value: 0x7f050050
			public const int print = 2131034192;
			
			// aapt resource value: 0x7f05002c
			public const int process_selected_text = 2131034156;
			
			// aapt resource value: 0x7f050043
			public const int save = 2131034179;
			
			// aapt resource value: 0x7f05002d
			public const int save_msg = 2131034157;
			
			// aapt resource value: 0x7f050044
			public const int saved_message = 2131034180;
			
			// aapt resource value: 0x7f05002e
			public const int simple_open_gl = 2131034158;
			
			// aapt resource value: 0x7f05002f
			public const int single_page = 2131034159;
			
			// aapt resource value: 0x7f050030
			public const int squiggly = 2131034160;
			
			// aapt resource value: 0x7f050000
			public const int status_bar_notification_info_overflow = 2131034112;
			
			// aapt resource value: 0x7f050031
			public const int strikeout = 2131034161;
			
			// aapt resource value: 0x7f050032
			public const int thumbnail_creation_running = 2131034162;
			
			// aapt resource value: 0x7f050033
			public const int todo_3d = 2131034163;
			
			// aapt resource value: 0x7f050034
			public const int todo_attachment = 2131034164;
			
			// aapt resource value: 0x7f050035
			public const int todo_java_script = 2131034165;
			
			// aapt resource value: 0x7f050036
			public const int todo_open_url = 2131034166;
			
			// aapt resource value: 0x7f050037
			public const int todo_play_movie = 2131034167;
			
			// aapt resource value: 0x7f050038
			public const int todo_play_sound = 2131034168;
			
			// aapt resource value: 0x7f050039
			public const int underline = 2131034169;
			
			// aapt resource value: 0x7f05003a
			public const int using_RGB_4444 = 2131034170;
			
			// aapt resource value: 0x7f05003b
			public const int using_RGB_565 = 2131034171;
			
			// aapt resource value: 0x7f05003c
			public const int vertical = 2131034172;
			
			// aapt resource value: 0x7f05003d
			public const int view_pager = 2131034173;
			
			// aapt resource value: 0x7f050045
			public const int warning = 2131034181;
			
			// aapt resource value: 0x7f05003e
			public const int yes = 2131034174;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f090007
			public const int AppBaseTheme = 2131296263;
			
			// aapt resource value: 0x7f090009
			public const int AppTheme = 2131296265;
			
			// aapt resource value: 0x7f090008
			public const int ProgressBar = 2131296264;
			
			// aapt resource value: 0x7f090000
			public const int TextAppearance_Compat_Notification = 2131296256;
			
			// aapt resource value: 0x7f090001
			public const int TextAppearance_Compat_Notification_Info = 2131296257;
			
			// aapt resource value: 0x7f090006
			public const int TextAppearance_Compat_Notification_Line2 = 2131296262;
			
			// aapt resource value: 0x7f090002
			public const int TextAppearance_Compat_Notification_Time = 2131296258;
			
			// aapt resource value: 0x7f090003
			public const int TextAppearance_Compat_Notification_Title = 2131296259;
			
			// aapt resource value: 0x7f090004
			public const int Widget_Compat_NotificationActionContainer = 2131296260;
			
			// aapt resource value: 0x7f090005
			public const int Widget_Compat_NotificationActionText = 2131296261;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] FontFamily = new int[] {
					2130771968,
					2130771969,
					2130771970,
					2130771971,
					2130771972,
					2130771973};
			
			// aapt resource value: 0
			public const int FontFamily_fontProviderAuthority = 0;
			
			// aapt resource value: 3
			public const int FontFamily_fontProviderCerts = 3;
			
			// aapt resource value: 4
			public const int FontFamily_fontProviderFetchStrategy = 4;
			
			// aapt resource value: 5
			public const int FontFamily_fontProviderFetchTimeout = 5;
			
			// aapt resource value: 1
			public const int FontFamily_fontProviderPackage = 1;
			
			// aapt resource value: 2
			public const int FontFamily_fontProviderQuery = 2;
			
			public static int[] FontFamilyFont = new int[] {
					2130771974,
					2130771975,
					2130771976};
			
			// aapt resource value: 1
			public const int FontFamilyFont_font = 1;
			
			// aapt resource value: 0
			public const int FontFamilyFont_fontStyle = 0;
			
			// aapt resource value: 2
			public const int FontFamilyFont_fontWeight = 2;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
