#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("RadaeePDFDemo.Resource", IsApplication=true)]

namespace RadaeePDFDemo
{
	
	
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Animation
		{
			
			// aapt resource value: 0x7F010000
			public const int anim_popup_end = 2130771968;
			
			// aapt resource value: 0x7F010001
			public const int anim_popup_start = 2130771969;
			
			static Animation()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Animation()
			{
			}
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7F020000
			public const int clearOnDoubleClick = 2130837504;
			
			// aapt resource value: 0x7F020001
			public const int penColor = 2130837505;
			
			// aapt resource value: 0x7F020002
			public const int penMaxWidth = 2130837506;
			
			// aapt resource value: 0x7F020003
			public const int penMinWidth = 2130837507;
			
			// aapt resource value: 0x7F020004
			public const int velocityFilterWeight = 2130837508;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Boolean
		{
			
			// aapt resource value: 0x7F030000
			public const int landscape_only = 2130903040;
			
			// aapt resource value: 0x7F030001
			public const int reader_fit_different_page_size = 2130903041;
			
			static Boolean()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Boolean()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7F040000
			public const int annot_menu_bg_color = 2130968576;
			
			// aapt resource value: 0x7F040001
			public const int bar_bg_color = 2130968577;
			
			// aapt resource value: 0x7F040002
			public const int bar_text_color = 2130968578;
			
			// aapt resource value: 0x7F040003
			public const int btn_disabled_color = 2130968579;
			
			// aapt resource value: 0x7F040004
			public const int btn_pressed_color = 2130968580;
			
			// aapt resource value: 0x7F040005
			public const int gridview_icon_color = 2130968581;
			
			// aapt resource value: 0x7F040006
			public const int menu_bg_color = 2130968582;
			
			// aapt resource value: 0x7F040007
			public const int menu_text_color = 2130968583;
			
			// aapt resource value: 0x7F040008
			public const int panel_bg_color = 2130968584;
			
			// aapt resource value: 0x7F040009
			public const int panel_text_color = 2130968585;
			
			// aapt resource value: 0x7F04000A
			public const int tab_bg_color = 2130968586;
			
			// aapt resource value: 0x7F04000B
			public const int tab_text_color = 2130968587;
			
			// aapt resource value: 0x7F04000C
			public const int toolbar_bg_color = 2130968588;
			
			// aapt resource value: 0x7F04000D
			public const int toolbar_icon_color = 2130968589;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7F050000
			public const int annot_menu_bar_margin = 2131034112;
			
			// aapt resource value: 0x7F050001
			public const int annot_menu_btn_size = 2131034113;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7F060000
			public const int bg_background = 2131099648;
			
			// aapt resource value: 0x7F060001
			public const int bg_btn_menu = 2131099649;
			
			// aapt resource value: 0x7F060002
			public const int bg_menu = 2131099650;
			
			// aapt resource value: 0x7F060003
			public const int btn_add_bookmark = 2131099651;
			
			// aapt resource value: 0x7F06000D
			public const int btn_annots = 2131099661;
			
			// aapt resource value: 0x7F060004
			public const int btn_annot_editbox = 2131099652;
			
			// aapt resource value: 0x7F060005
			public const int btn_annot_ellipse = 2131099653;
			
			// aapt resource value: 0x7F060006
			public const int btn_annot_ink = 2131099654;
			
			// aapt resource value: 0x7F060007
			public const int btn_annot_line = 2131099655;
			
			// aapt resource value: 0x7F060008
			public const int btn_annot_note = 2131099656;
			
			// aapt resource value: 0x7F060009
			public const int btn_annot_polygon = 2131099657;
			
			// aapt resource value: 0x7F06000A
			public const int btn_annot_polyline = 2131099658;
			
			// aapt resource value: 0x7F06000B
			public const int btn_annot_rect = 2131099659;
			
			// aapt resource value: 0x7F06000C
			public const int btn_annot_stamp = 2131099660;
			
			// aapt resource value: 0x7F06000E
			public const int btn_back = 2131099662;
			
			// aapt resource value: 0x7F06000F
			public const int btn_cancel = 2131099663;
			
			// aapt resource value: 0x7F060010
			public const int btn_done = 2131099664;
			
			// aapt resource value: 0x7F060011
			public const int btn_left = 2131099665;
			
			// aapt resource value: 0x7F060012
			public const int btn_more = 2131099666;
			
			// aapt resource value: 0x7F060013
			public const int btn_outline = 2131099667;
			
			// aapt resource value: 0x7F060014
			public const int btn_perform = 2131099668;
			
			// aapt resource value: 0x7F060015
			public const int btn_print = 2131099669;
			
			// aapt resource value: 0x7F060016
			public const int btn_redo = 2131099670;
			
			// aapt resource value: 0x7F060017
			public const int btn_remove = 2131099671;
			
			// aapt resource value: 0x7F060018
			public const int btn_right = 2131099672;
			
			// aapt resource value: 0x7F060019
			public const int btn_save = 2131099673;
			
			// aapt resource value: 0x7F06001A
			public const int btn_search = 2131099674;
			
			// aapt resource value: 0x7F06001B
			public const int btn_select = 2131099675;
			
			// aapt resource value: 0x7F06001C
			public const int btn_settings = 2131099676;
			
			// aapt resource value: 0x7F06001D
			public const int btn_share = 2131099677;
			
			// aapt resource value: 0x7F06001E
			public const int btn_show_bookmarks = 2131099678;
			
			// aapt resource value: 0x7F06001F
			public const int btn_undo = 2131099679;
			
			// aapt resource value: 0x7F060020
			public const int btn_view = 2131099680;
			
			// aapt resource value: 0x7F060021
			public const int btn_view_dual = 2131099681;
			
			// aapt resource value: 0x7F060022
			public const int btn_view_horz = 2131099682;
			
			// aapt resource value: 0x7F060023
			public const int btn_view_single = 2131099683;
			
			// aapt resource value: 0x7F060024
			public const int btn_view_vert = 2131099684;
			
			// aapt resource value: 0x7F06002A
			public const int Icon = 2131099690;
			
			// aapt resource value: 0x7F060025
			public const int ic_custom_stamp = 2131099685;
			
			// aapt resource value: 0x7F060026
			public const int ic_grid_file = 2131099686;
			
			// aapt resource value: 0x7F060027
			public const int ic_grid_folder0 = 2131099687;
			
			// aapt resource value: 0x7F060028
			public const int ic_grid_folder1 = 2131099688;
			
			// aapt resource value: 0x7F060029
			public const int ic_grid_folder2 = 2131099689;
			
			// aapt resource value: 0x7F06002B
			public const int pt_end = 2131099691;
			
			// aapt resource value: 0x7F06002C
			public const int pt_start = 2131099692;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7F070000
			public const int activate = 2131165184;
			
			// aapt resource value: 0x7F070001
			public const int actual_content = 2131165185;
			
			// aapt resource value: 0x7F070002
			public const int add_bookmark = 2131165186;
			
			// aapt resource value: 0x7F070003
			public const int add_bookmark_icon = 2131165187;
			
			// aapt resource value: 0x7F070004
			public const int annot_combo = 2131165188;
			
			// aapt resource value: 0x7F070005
			public const int annot_text = 2131165189;
			
			// aapt resource value: 0x7F070006
			public const int bar_top = 2131165190;
			
			// aapt resource value: 0x7F070007
			public const int btn_annot = 2131165191;
			
			// aapt resource value: 0x7F070008
			public const int btn_annot_edit = 2131165192;
			
			// aapt resource value: 0x7F070009
			public const int btn_annot_editbox = 2131165193;
			
			// aapt resource value: 0x7F07000A
			public const int btn_annot_ink = 2131165194;
			
			// aapt resource value: 0x7F07000B
			public const int btn_annot_line = 2131165195;
			
			// aapt resource value: 0x7F07000C
			public const int btn_annot_note = 2131165196;
			
			// aapt resource value: 0x7F07000D
			public const int btn_annot_oval = 2131165197;
			
			// aapt resource value: 0x7F07000E
			public const int btn_annot_perform = 2131165198;
			
			// aapt resource value: 0x7F07000F
			public const int btn_annot_polygon = 2131165199;
			
			// aapt resource value: 0x7F070010
			public const int btn_annot_polyline = 2131165200;
			
			// aapt resource value: 0x7F070011
			public const int btn_annot_property = 2131165201;
			
			// aapt resource value: 0x7F070012
			public const int btn_annot_rect = 2131165202;
			
			// aapt resource value: 0x7F070013
			public const int btn_annot_remove = 2131165203;
			
			// aapt resource value: 0x7F070014
			public const int btn_annot_stamp = 2131165204;
			
			// aapt resource value: 0x7F070015
			public const int btn_back = 2131165205;
			
			// aapt resource value: 0x7F070016
			public const int btn_browser = 2131165206;
			
			// aapt resource value: 0x7F070017
			public const int btn_cancel = 2131165207;
			
			// aapt resource value: 0x7F070018
			public const int btn_clear = 2131165208;
			
			// aapt resource value: 0x7F070019
			public const int btn_edit = 2131165209;
			
			// aapt resource value: 0x7F07001A
			public const int btn_fcolor = 2131165210;
			
			// aapt resource value: 0x7F07001B
			public const int btn_files = 2131165211;
			
			// aapt resource value: 0x7F07001C
			public const int btn_find = 2131165212;
			
			// aapt resource value: 0x7F07001D
			public const int btn_goto = 2131165213;
			
			// aapt resource value: 0x7F07001E
			public const int btn_icon = 2131165214;
			
			// aapt resource value: 0x7F07001F
			public const int btn_lcolor = 2131165215;
			
			// aapt resource value: 0x7F070020
			public const int btn_left = 2131165216;
			
			// aapt resource value: 0x7F070021
			public const int btn_lhead1 = 2131165217;
			
			// aapt resource value: 0x7F070022
			public const int btn_lhead2 = 2131165218;
			
			// aapt resource value: 0x7F070023
			public const int btn_lstyle = 2131165219;
			
			// aapt resource value: 0x7F070024
			public const int btn_more = 2131165220;
			
			// aapt resource value: 0x7F070025
			public const int btn_nav = 2131165221;
			
			// aapt resource value: 0x7F070026
			public const int btn_ok = 2131165222;
			
			// aapt resource value: 0x7F070027
			public const int btn_outline = 2131165223;
			
			// aapt resource value: 0x7F070028
			public const int btn_perform = 2131165224;
			
			// aapt resource value: 0x7F070029
			public const int btn_recent = 2131165225;
			
			// aapt resource value: 0x7F07002A
			public const int btn_redo = 2131165226;
			
			// aapt resource value: 0x7F07002B
			public const int btn_refresh = 2131165227;
			
			// aapt resource value: 0x7F07002C
			public const int btn_remove = 2131165228;
			
			// aapt resource value: 0x7F07002D
			public const int btn_remove_rec = 2131165229;
			
			// aapt resource value: 0x7F07002E
			public const int btn_right = 2131165230;
			
			// aapt resource value: 0x7F07002F
			public const int btn_select = 2131165231;
			
			// aapt resource value: 0x7F070030
			public const int btn_share = 2131165232;
			
			// aapt resource value: 0x7F070031
			public const int btn_undo = 2131165233;
			
			// aapt resource value: 0x7F070032
			public const int btn_up = 2131165234;
			
			// aapt resource value: 0x7F070033
			public const int btn_view = 2131165235;
			
			// aapt resource value: 0x7F070034
			public const int chk_lock = 2131165236;
			
			// aapt resource value: 0x7F070035
			public const int chk_show = 2131165237;
			
			// aapt resource value: 0x7F070036
			public const int delete = 2131165238;
			
			// aapt resource value: 0x7F070037
			public const int dlg_input = 2131165239;
			
			// aapt resource value: 0x7F070038
			public const int dlg_show_note = 2131165240;
			
			// aapt resource value: 0x7F070039
			public const int edit_lwidth = 2131165241;
			
			// aapt resource value: 0x7F07003A
			public const int edit_pages = 2131165242;
			
			// aapt resource value: 0x7F07003B
			public const int edit_pages_icon = 2131165243;
			
			// aapt resource value: 0x7F07003C
			public const int edit_path = 2131165244;
			
			// aapt resource value: 0x7F07003D
			public const int edit_pswd = 2131165245;
			
			// aapt resource value: 0x7F07003E
			public const int fb_view = 2131165246;
			
			// aapt resource value: 0x7F07003F
			public const int img_00 = 2131165247;
			
			// aapt resource value: 0x7F070040
			public const int img_01 = 2131165248;
			
			// aapt resource value: 0x7F070041
			public const int img_02 = 2131165249;
			
			// aapt resource value: 0x7F070042
			public const int img_03 = 2131165250;
			
			// aapt resource value: 0x7F070043
			public const int img_04 = 2131165251;
			
			// aapt resource value: 0x7F070044
			public const int img_05 = 2131165252;
			
			// aapt resource value: 0x7F070045
			public const int img_06 = 2131165253;
			
			// aapt resource value: 0x7F070046
			public const int img_07 = 2131165254;
			
			// aapt resource value: 0x7F070047
			public const int img_08 = 2131165255;
			
			// aapt resource value: 0x7F070048
			public const int img_09 = 2131165256;
			
			// aapt resource value: 0x7F070049
			public const int img_10 = 2131165257;
			
			// aapt resource value: 0x7F07004A
			public const int img_11 = 2131165258;
			
			// aapt resource value: 0x7F07004B
			public const int img_12 = 2131165259;
			
			// aapt resource value: 0x7F07004C
			public const int img_13 = 2131165260;
			
			// aapt resource value: 0x7F07004D
			public const int img_14 = 2131165261;
			
			// aapt resource value: 0x7F07004E
			public const int img_15 = 2131165262;
			
			// aapt resource value: 0x7F07004F
			public const int img_delete = 2131165263;
			
			// aapt resource value: 0x7F070050
			public const int img_more = 2131165264;
			
			// aapt resource value: 0x7F070051
			public const int img_page = 2131165265;
			
			// aapt resource value: 0x7F070052
			public const int img_rotate = 2131165266;
			
			// aapt resource value: 0x7F070053
			public const int img_thumb = 2131165267;
			
			// aapt resource value: 0x7F070057
			public const int label = 2131165271;
			
			// aapt resource value: 0x7F070054
			public const int lab_content = 2131165268;
			
			// aapt resource value: 0x7F070055
			public const int lab_page = 2131165269;
			
			// aapt resource value: 0x7F070056
			public const int lab_subj = 2131165270;
			
			// aapt resource value: 0x7F070058
			public const int lay_bar = 2131165272;
			
			// aapt resource value: 0x7F070059
			public const int lay_panel = 2131165273;
			
			// aapt resource value: 0x7F07005A
			public const int lay_root = 2131165274;
			
			// aapt resource value: 0x7F07005B
			public const int lst_files = 2131165275;
			
			// aapt resource value: 0x7F07005C
			public const int lst_outline = 2131165276;
			
			// aapt resource value: 0x7F07005D
			public const int open = 2131165277;
			
			// aapt resource value: 0x7F07005E
			public const int open_assets = 2131165278;
			
			// aapt resource value: 0x7F07005F
			public const int open_http = 2131165279;
			
			// aapt resource value: 0x7F070060
			public const int pdf_nav = 2131165280;
			
			// aapt resource value: 0x7F070061
			public const int pdf_pager = 2131165281;
			
			// aapt resource value: 0x7F070062
			public const int pdf_view = 2131165282;
			
			// aapt resource value: 0x7F070063
			public const int print = 2131165283;
			
			// aapt resource value: 0x7F070064
			public const int print_icon = 2131165284;
			
			// aapt resource value: 0x7F070065
			public const int progress = 2131165285;
			
			// aapt resource value: 0x7F070066
			public const int rad_copy = 2131165286;
			
			// aapt resource value: 0x7F070067
			public const int rad_group = 2131165287;
			
			// aapt resource value: 0x7F070068
			public const int rad_highlight = 2131165288;
			
			// aapt resource value: 0x7F070069
			public const int rad_squiggly = 2131165289;
			
			// aapt resource value: 0x7F07006A
			public const int rad_strikeout = 2131165290;
			
			// aapt resource value: 0x7F07006B
			public const int rad_underline = 2131165291;
			
			// aapt resource value: 0x7F07006C
			public const int save = 2131165292;
			
			// aapt resource value: 0x7F07006D
			public const int save_icon = 2131165293;
			
			// aapt resource value: 0x7F07006E
			public const int seek_alpha = 2131165294;
			
			// aapt resource value: 0x7F07006F
			public const int seek_clr_b = 2131165295;
			
			// aapt resource value: 0x7F070070
			public const int seek_clr_g = 2131165296;
			
			// aapt resource value: 0x7F070071
			public const int seek_clr_r = 2131165297;
			
			// aapt resource value: 0x7F070072
			public const int seek_page = 2131165298;
			
			// aapt resource value: 0x7F070073
			public const int share = 2131165299;
			
			// aapt resource value: 0x7F070074
			public const int share_icon = 2131165300;
			
			// aapt resource value: 0x7F070075
			public const int show_bookmarks = 2131165301;
			
			// aapt resource value: 0x7F070076
			public const int show_bookmarks_icon = 2131165302;
			
			// aapt resource value: 0x7F070077
			public const int sign_pad = 2131165303;
			
			// aapt resource value: 0x7F070078
			public const int thumb_view = 2131165304;
			
			// aapt resource value: 0x7F070079
			public const int tog_enable = 2131165305;
			
			// aapt resource value: 0x7F07007A
			public const int txt_alpha = 2131165306;
			
			// aapt resource value: 0x7F07007B
			public const int txt_alpha_val = 2131165307;
			
			// aapt resource value: 0x7F07007C
			public const int txt_cert = 2131165308;
			
			// aapt resource value: 0x7F07007D
			public const int txt_clr_b = 2131165309;
			
			// aapt resource value: 0x7F07007E
			public const int txt_clr_g = 2131165310;
			
			// aapt resource value: 0x7F07007F
			public const int txt_clr_r = 2131165311;
			
			// aapt resource value: 0x7F070080
			public const int txt_contact = 2131165312;
			
			// aapt resource value: 0x7F070081
			public const int txt_content = 2131165313;
			
			// aapt resource value: 0x7F070082
			public const int txt_enable = 2131165314;
			
			// aapt resource value: 0x7F070083
			public const int txt_fcolor = 2131165315;
			
			// aapt resource value: 0x7F070084
			public const int txt_filter = 2131165316;
			
			// aapt resource value: 0x7F070085
			public const int txt_find = 2131165317;
			
			// aapt resource value: 0x7F070086
			public const int txt_ftype = 2131165318;
			
			// aapt resource value: 0x7F070087
			public const int txt_head = 2131165319;
			
			// aapt resource value: 0x7F070088
			public const int txt_hwriting = 2131165320;
			
			// aapt resource value: 0x7F070089
			public const int txt_icon = 2131165321;
			
			// aapt resource value: 0x7F07008A
			public const int txt_info = 2131165322;
			
			// aapt resource value: 0x7F07008B
			public const int txt_issue = 2131165323;
			
			// aapt resource value: 0x7F07008C
			public const int txt_lhead1 = 2131165324;
			
			// aapt resource value: 0x7F07008D
			public const int txt_lhead2 = 2131165325;
			
			// aapt resource value: 0x7F07008E
			public const int txt_location = 2131165326;
			
			// aapt resource value: 0x7F07008F
			public const int txt_lstyle = 2131165327;
			
			// aapt resource value: 0x7F070090
			public const int txt_lwidth = 2131165328;
			
			// aapt resource value: 0x7F070091
			public const int txt_mod = 2131165329;
			
			// aapt resource value: 0x7F070092
			public const int txt_name = 2131165330;
			
			// aapt resource value: 0x7F070093
			public const int txt_no_files = 2131165331;
			
			// aapt resource value: 0x7F070094
			public const int txt_no_recent = 2131165332;
			
			// aapt resource value: 0x7F070095
			public const int txt_password = 2131165333;
			
			// aapt resource value: 0x7F070096
			public const int txt_path = 2131165334;
			
			// aapt resource value: 0x7F070097
			public const int txt_pswd = 2131165335;
			
			// aapt resource value: 0x7F070098
			public const int txt_reason = 2131165336;
			
			// aapt resource value: 0x7F070099
			public const int txt_subj = 2131165337;
			
			// aapt resource value: 0x7F07009A
			public const int txt_subject = 2131165338;
			
			// aapt resource value: 0x7F07009B
			public const int txt_verify = 2131165339;
			
			// aapt resource value: 0x7F07009C
			public const int txt_version = 2131165340;
			
			// aapt resource value: 0x7F07009D
			public const int view_00 = 2131165341;
			
			// aapt resource value: 0x7F07009E
			public const int view_01 = 2131165342;
			
			// aapt resource value: 0x7F07009F
			public const int view_02 = 2131165343;
			
			// aapt resource value: 0x7F0700A0
			public const int view_03 = 2131165344;
			
			// aapt resource value: 0x7F0700A1
			public const int view_04 = 2131165345;
			
			// aapt resource value: 0x7F0700A2
			public const int view_05 = 2131165346;
			
			// aapt resource value: 0x7F0700A3
			public const int view_06 = 2131165347;
			
			// aapt resource value: 0x7F0700A4
			public const int view_07 = 2131165348;
			
			// aapt resource value: 0x7F0700A5
			public const int view_08 = 2131165349;
			
			// aapt resource value: 0x7F0700A6
			public const int view_09 = 2131165350;
			
			// aapt resource value: 0x7F0700A7
			public const int view_10 = 2131165351;
			
			// aapt resource value: 0x7F0700A8
			public const int view_11 = 2131165352;
			
			// aapt resource value: 0x7F0700A9
			public const int view_12 = 2131165353;
			
			// aapt resource value: 0x7F0700AA
			public const int view_13 = 2131165354;
			
			// aapt resource value: 0x7F0700AB
			public const int view_14 = 2131165355;
			
			// aapt resource value: 0x7F0700AC
			public const int view_15 = 2131165356;
			
			// aapt resource value: 0x7F0700AD
			public const int view_dual = 2131165357;
			
			// aapt resource value: 0x7F0700AE
			public const int view_dual_icon = 2131165358;
			
			// aapt resource value: 0x7F0700AF
			public const int view_horz = 2131165359;
			
			// aapt resource value: 0x7F0700B0
			public const int view_horz_icon = 2131165360;
			
			// aapt resource value: 0x7F0700B1
			public const int view_single = 2131165361;
			
			// aapt resource value: 0x7F0700B2
			public const int view_single_icon = 2131165362;
			
			// aapt resource value: 0x7F0700B3
			public const int view_vert = 2131165363;
			
			// aapt resource value: 0x7F0700B4
			public const int view_vert_icon = 2131165364;
			
			// aapt resource value: 0x7F0700B5
			public const int vw_files = 2131165365;
			
			// aapt resource value: 0x7F0700B6
			public const int vw_grid = 2131165366;
			
			// aapt resource value: 0x7F0700B7
			public const int vw_ldash11 = 2131165367;
			
			// aapt resource value: 0x7F0700B8
			public const int vw_ldash16242 = 2131165368;
			
			// aapt resource value: 0x7F0700B9
			public const int vw_ldash22 = 2131165369;
			
			// aapt resource value: 0x7F0700BA
			public const int vw_ldash4222 = 2131165370;
			
			// aapt resource value: 0x7F0700BB
			public const int vw_ldash44 = 2131165371;
			
			// aapt resource value: 0x7F0700BC
			public const int vw_lhead0 = 2131165372;
			
			// aapt resource value: 0x7F0700BD
			public const int vw_lhead1 = 2131165373;
			
			// aapt resource value: 0x7F0700BE
			public const int vw_lhead2 = 2131165374;
			
			// aapt resource value: 0x7F0700BF
			public const int vw_lhead3 = 2131165375;
			
			// aapt resource value: 0x7F0700C0
			public const int vw_lhead4 = 2131165376;
			
			// aapt resource value: 0x7F0700C1
			public const int vw_lhead5 = 2131165377;
			
			// aapt resource value: 0x7F0700C2
			public const int vw_lhead6 = 2131165378;
			
			// aapt resource value: 0x7F0700C3
			public const int vw_lhead7 = 2131165379;
			
			// aapt resource value: 0x7F0700C4
			public const int vw_lhead8 = 2131165380;
			
			// aapt resource value: 0x7F0700C5
			public const int vw_lhead9 = 2131165381;
			
			// aapt resource value: 0x7F0700C6
			public const int vw_lsolid = 2131165382;
			
			// aapt resource value: 0x7F0700C7
			public const int vw_menu_back = 2131165383;
			
			// aapt resource value: 0x7F0700C8
			public const int vw_pages = 2131165384;
			
			// aapt resource value: 0x7F0700C9
			public const int vw_recent = 2131165385;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7F080000
			public const int bar_act = 2131230720;
			
			// aapt resource value: 0x7F080001
			public const int bar_annot = 2131230721;
			
			// aapt resource value: 0x7F080002
			public const int bar_cmd = 2131230722;
			
			// aapt resource value: 0x7F080003
			public const int bar_find = 2131230723;
			
			// aapt resource value: 0x7F080004
			public const int bar_menu_file = 2131230724;
			
			// aapt resource value: 0x7F080005
			public const int bar_menu_recent = 2131230725;
			
			// aapt resource value: 0x7F080006
			public const int bar_seek = 2131230726;
			
			// aapt resource value: 0x7F080007
			public const int bar_thumb_view = 2131230727;
			
			// aapt resource value: 0x7F080008
			public const int dlg_annot_popup = 2131230728;
			
			// aapt resource value: 0x7F080009
			public const int dlg_annot_prop_comm = 2131230729;
			
			// aapt resource value: 0x7F08000A
			public const int dlg_annot_prop_icon = 2131230730;
			
			// aapt resource value: 0x7F08000B
			public const int dlg_annot_prop_line = 2131230731;
			
			// aapt resource value: 0x7F08000C
			public const int dlg_annot_prop_markup = 2131230732;
			
			// aapt resource value: 0x7F08000D
			public const int dlg_annot_signature = 2131230733;
			
			// aapt resource value: 0x7F08000E
			public const int dlg_annot_signprop = 2131230734;
			
			// aapt resource value: 0x7F08000F
			public const int dlg_browser = 2131230735;
			
			// aapt resource value: 0x7F080010
			public const int dlg_note = 2131230736;
			
			// aapt resource value: 0x7F080011
			public const int dlg_outline = 2131230737;
			
			// aapt resource value: 0x7F080012
			public const int dlg_pswd = 2131230738;
			
			// aapt resource value: 0x7F080013
			public const int dlg_text = 2131230739;
			
			// aapt resource value: 0x7F080014
			public const int item_bookmark = 2131230740;
			
			// aapt resource value: 0x7F080015
			public const int item_dir_list = 2131230741;
			
			// aapt resource value: 0x7F080016
			public const int item_file_grid = 2131230742;
			
			// aapt resource value: 0x7F080017
			public const int item_file_list = 2131230743;
			
			// aapt resource value: 0x7F080018
			public const int item_outline = 2131230744;
			
			// aapt resource value: 0x7F080019
			public const int item_page = 2131230745;
			
			// aapt resource value: 0x7F08001A
			public const int Main = 2131230746;
			
			// aapt resource value: 0x7F08001B
			public const int pdf_files = 2131230747;
			
			// aapt resource value: 0x7F08001C
			public const int pdf_fragment = 2131230748;
			
			// aapt resource value: 0x7F08001D
			public const int pdf_gllayout = 2131230749;
			
			// aapt resource value: 0x7F08001E
			public const int pdf_layout = 2131230750;
			
			// aapt resource value: 0x7F08001F
			public const int pdf_main = 2131230751;
			
			// aapt resource value: 0x7F080020
			public const int pdf_nav = 2131230752;
			
			// aapt resource value: 0x7F080021
			public const int pdf_navigate = 2131230753;
			
			// aapt resource value: 0x7F080022
			public const int pdf_pages = 2131230754;
			
			// aapt resource value: 0x7F080023
			public const int pdf_recent = 2131230755;
			
			// aapt resource value: 0x7F080024
			public const int pdf_thumb_grid_view = 2131230756;
			
			// aapt resource value: 0x7F080025
			public const int pop_annot = 2131230757;
			
			// aapt resource value: 0x7F080026
			public const int pop_bookmark_menu = 2131230758;
			
			// aapt resource value: 0x7F080027
			public const int pop_color = 2131230759;
			
			// aapt resource value: 0x7F080028
			public const int pop_combo = 2131230760;
			
			// aapt resource value: 0x7F080029
			public const int pop_edit = 2131230761;
			
			// aapt resource value: 0x7F08002A
			public const int pop_icon_attach = 2131230762;
			
			// aapt resource value: 0x7F08002B
			public const int pop_icon_text = 2131230763;
			
			// aapt resource value: 0x7F08002C
			public const int pop_lhead = 2131230764;
			
			// aapt resource value: 0x7F08002D
			public const int pop_lstyle = 2131230765;
			
			// aapt resource value: 0x7F08002E
			public const int pop_more = 2131230766;
			
			// aapt resource value: 0x7F08002F
			public const int pop_view = 2131230767;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Raw
		{
			
			// aapt resource value: 0x7F090000
			public const int amiri_regular = 2131296256;
			
			// aapt resource value: 0x7F090001
			public const int arimo = 2131296257;
			
			// aapt resource value: 0x7F090002
			public const int arimob = 2131296258;
			
			// aapt resource value: 0x7F090003
			public const int arimobi = 2131296259;
			
			// aapt resource value: 0x7F090004
			public const int arimoi = 2131296260;
			
			// aapt resource value: 0x7F090005
			public const int cmaps = 2131296261;
			
			// aapt resource value: 0x7F090006
			public const int cmyk_rgb = 2131296262;
			
			// aapt resource value: 0x7F090007
			public const int cousine = 2131296263;
			
			// aapt resource value: 0x7F090008
			public const int cousineb = 2131296264;
			
			// aapt resource value: 0x7F090009
			public const int cousinebi = 2131296265;
			
			// aapt resource value: 0x7F09000A
			public const int cousinei = 2131296266;
			
			// aapt resource value: 0x7F09000B
			public const int droidsanschinese = 2131296267;
			
			// aapt resource value: 0x7F09000C
			public const int radaee_test = 2131296268;
			
			// aapt resource value: 0x7F09000D
			public const int rdf013 = 2131296269;
			
			// aapt resource value: 0x7F09000E
			public const int symbol = 2131296270;
			
			// aapt resource value: 0x7F09000F
			public const int texgy = 2131296271;
			
			// aapt resource value: 0x7F090010
			public const int texgyb = 2131296272;
			
			// aapt resource value: 0x7F090011
			public const int texgybi = 2131296273;
			
			// aapt resource value: 0x7F090012
			public const int texgyi = 2131296274;
			
			// aapt resource value: 0x7F090013
			public const int tinos = 2131296275;
			
			// aapt resource value: 0x7F090014
			public const int tinosb = 2131296276;
			
			// aapt resource value: 0x7F090015
			public const int tinosbi = 2131296277;
			
			// aapt resource value: 0x7F090016
			public const int tinosi = 2131296278;
			
			// aapt resource value: 0x7F090017
			public const int umaps = 2131296279;
			
			static Raw()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Raw()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7F0A0002
			public const int about = 2131361794;
			
			// aapt resource value: 0x7F0A0003
			public const int advance = 2131361795;
			
			// aapt resource value: 0x7F0A0004
			public const int alpha = 2131361796;
			
			// aapt resource value: 0x7F0A000B
			public const int annotation_failed = 2131361803;
			
			// aapt resource value: 0x7F0A0005
			public const int annot_color = 2131361797;
			
			// aapt resource value: 0x7F0A0006
			public const int annot_edit = 2131361798;
			
			// aapt resource value: 0x7F0A0007
			public const int annot_lock = 2131361799;
			
			// aapt resource value: 0x7F0A0008
			public const int annot_perform = 2131361800;
			
			// aapt resource value: 0x7F0A0009
			public const int annot_property = 2131361801;
			
			// aapt resource value: 0x7F0A000A
			public const int annot_remove = 2131361802;
			
			// aapt resource value: 0x7F0A0000
			public const int ApplicationName = 2131361792;
			
			// aapt resource value: 0x7F0A000C
			public const int app_name = 2131361804;
			
			// aapt resource value: 0x7F0A0014
			public const int bookmarks = 2131361812;
			
			// aapt resource value: 0x7F0A000D
			public const int bookmark_add = 2131361805;
			
			// aapt resource value: 0x7F0A000E
			public const int bookmark_already_added = 2131361806;
			
			// aapt resource value: 0x7F0A000F
			public const int bookmark_error = 2131361807;
			
			// aapt resource value: 0x7F0A0010
			public const int bookmark_label = 2131361808;
			
			// aapt resource value: 0x7F0A0011
			public const int bookmark_remove_error = 2131361809;
			
			// aapt resource value: 0x7F0A0012
			public const int bookmark_show = 2131361810;
			
			// aapt resource value: 0x7F0A0013
			public const int bookmark_success = 2131361811;
			
			// aapt resource value: 0x7F0A0017
			public const int browser_file_delete = 2131361815;
			
			// aapt resource value: 0x7F0A0018
			public const int browser_file_delete_confirm = 2131361816;
			
			// aapt resource value: 0x7F0A0019
			public const int browser_file_delete_recent = 2131361817;
			
			// aapt resource value: 0x7F0A001A
			public const int browser_file_delete_recent_list_confirm = 2131361818;
			
			// aapt resource value: 0x7F0A001B
			public const int browser_file_recent = 2131361819;
			
			// aapt resource value: 0x7F0A001C
			public const int browser_file_share = 2131361820;
			
			// aapt resource value: 0x7F0A0015
			public const int browse_open_file = 2131361813;
			
			// aapt resource value: 0x7F0A0016
			public const int browse_open_glfile = 2131361814;
			
			// aapt resource value: 0x7F0A001D
			public const int button_ok_label = 2131361821;
			
			// aapt resource value: 0x7F0A001E
			public const int cancel = 2131361822;
			
			// aapt resource value: 0x7F0A001F
			public const int cannot_write_or_encrypted = 2131361823;
			
			// aapt resource value: 0x7F0A0020
			public const int catalog_not_found = 2131361824;
			
			// aapt resource value: 0x7F0A0021
			public const int clear = 2131361825;
			
			// aapt resource value: 0x7F0A0022
			public const int confirm = 2131361826;
			
			// aapt resource value: 0x7F0A0023
			public const int copy_text = 2131361827;
			
			// aapt resource value: 0x7F0A0024
			public const int copy_text_to_clipboard = 2131361828;
			
			// aapt resource value: 0x7F0A0025
			public const int create_pdf = 2131361829;
			
			// aapt resource value: 0x7F0A0026
			public const int curl = 2131361830;
			
			// aapt resource value: 0x7F0A0027
			public const int curl_pages = 2131361831;
			
			// aapt resource value: 0x7F0A0028
			public const int delete = 2131361832;
			
			// aapt resource value: 0x7F0A0029
			public const int delete_signature_message = 2131361833;
			
			// aapt resource value: 0x7F0A002A
			public const int dual_page = 2131361834;
			
			// aapt resource value: 0x7F0A002B
			public const int edit_catalog_failed = 2131361835;
			
			// aapt resource value: 0x7F0A002C
			public const int exiting = 2131361836;
			
			// aapt resource value: 0x7F0A002D
			public const int failed_encryption = 2131361837;
			
			// aapt resource value: 0x7F0A002E
			public const int failed_invalid_format = 2131361838;
			
			// aapt resource value: 0x7F0A002F
			public const int failed_invalid_password = 2131361839;
			
			// aapt resource value: 0x7F0A0030
			public const int failed_invalid_path = 2131361840;
			
			// aapt resource value: 0x7F0A0031
			public const int failed_unknown = 2131361841;
			
			// aapt resource value: 0x7F0A0032
			public const int file_not_exist = 2131361842;
			
			// aapt resource value: 0x7F0A0033
			public const int file_not_exist_error = 2131361843;
			
			// aapt resource value: 0x7F0A0034
			public const int file_not_opened = 2131361844;
			
			// aapt resource value: 0x7F0A0035
			public const int fill_color = 2131361845;
			
			// aapt resource value: 0x7F0A0001
			public const int Hello = 2131361793;
			
			// aapt resource value: 0x7F0A0036
			public const int highlight_texts = 2131361846;
			
			// aapt resource value: 0x7F0A0037
			public const int horizontal = 2131361847;
			
			// aapt resource value: 0x7F0A0038
			public const int icon = 2131361848;
			
			// aapt resource value: 0x7F0A0039
			public const int input_password = 2131361849;
			
			// aapt resource value: 0x7F0A003A
			public const int javascript = 2131361850;
			
			// aapt resource value: 0x7F0A003B
			public const int line_color = 2131361851;
			
			// aapt resource value: 0x7F0A003C
			public const int line_end = 2131361852;
			
			// aapt resource value: 0x7F0A003D
			public const int line_start = 2131361853;
			
			// aapt resource value: 0x7F0A003E
			public const int line_style = 2131361854;
			
			// aapt resource value: 0x7F0A003F
			public const int line_width = 2131361855;
			
			// aapt resource value: 0x7F0A0040
			public const int loading = 2131361856;
			
			// aapt resource value: 0x7F0A0041
			public const int loading_pdf = 2131361857;
			
			// aapt resource value: 0x7F0A0042
			public const int no = 2131361858;
			
			// aapt resource value: 0x7F0A0049
			public const int note_content = 2131361865;
			
			// aapt resource value: 0x7F0A004A
			public const int note_subject = 2131361866;
			
			// aapt resource value: 0x7F0A004B
			public const int note_text = 2131361867;
			
			// aapt resource value: 0x7F0A0043
			public const int no_bookmarks = 2131361859;
			
			// aapt resource value: 0x7F0A0044
			public const int no_more_found = 2131361860;
			
			// aapt resource value: 0x7F0A0045
			public const int no_more_redo = 2131361861;
			
			// aapt resource value: 0x7F0A0046
			public const int no_more_undo = 2131361862;
			
			// aapt resource value: 0x7F0A0047
			public const int no_pdf_outlines = 2131361863;
			
			// aapt resource value: 0x7F0A0048
			public const int no_search_reflow = 2131361864;
			
			// aapt resource value: 0x7F0A004C
			public const int ok = 2131361868;
			
			// aapt resource value: 0x7F0A004D
			public const int open_asset = 2131361869;
			
			// aapt resource value: 0x7F0A004E
			public const int open_http = 2131361870;
			
			// aapt resource value: 0x7F0A004F
			public const int open_sdcard = 2131361871;
			
			// aapt resource value: 0x7F0A0051
			public const int pages_list = 2131361873;
			
			// aapt resource value: 0x7F0A0050
			public const int page_change_block = 2131361872;
			
			// aapt resource value: 0x7F0A0052
			public const int pdf_outline = 2131361874;
			
			// aapt resource value: 0x7F0A0053
			public const int pdf_print_calculation_failed = 2131361875;
			
			// aapt resource value: 0x7F0A0054
			public const int pdf_print_not_available = 2131361876;
			
			// aapt resource value: 0x7F0A0055
			public const int pdf_share_not_available = 2131361877;
			
			// aapt resource value: 0x7F0A0056
			public const int permission_denied_content = 2131361878;
			
			// aapt resource value: 0x7F0A0057
			public const int permission_dialog_content = 2131361879;
			
			// aapt resource value: 0x7F0A0058
			public const int permission_dialog_title = 2131361880;
			
			// aapt resource value: 0x7F0A0059
			public const int please_wait = 2131361881;
			
			// aapt resource value: 0x7F0A005A
			public const int print = 2131361882;
			
			// aapt resource value: 0x7F0A005B
			public const int process_selected_text = 2131361883;
			
			// aapt resource value: 0x7F0A005C
			public const int read_only_annotation = 2131361884;
			
			// aapt resource value: 0x7F0A005D
			public const int reflow = 2131361885;
			
			// aapt resource value: 0x7F0A005E
			public const int save = 2131361886;
			
			// aapt resource value: 0x7F0A0060
			public const int saved_message = 2131361888;
			
			// aapt resource value: 0x7F0A005F
			public const int save_msg = 2131361887;
			
			// aapt resource value: 0x7F0A0061
			public const int share = 2131361889;
			
			// aapt resource value: 0x7F0A0062
			public const int show_password = 2131361890;
			
			// aapt resource value: 0x7F0A0063
			public const int sign_certificate = 2131361891;
			
			// aapt resource value: 0x7F0A0064
			public const int sign_certificate_filetype = 2131361892;
			
			// aapt resource value: 0x7F0A0065
			public const int sign_certificate_hand = 2131361893;
			
			// aapt resource value: 0x7F0A0066
			public const int sign_certificate_password = 2131361894;
			
			// aapt resource value: 0x7F0A0067
			public const int sign_certificate_select = 2131361895;
			
			// aapt resource value: 0x7F0A0068
			public const int sign_error_fail = 2131361896;
			
			// aapt resource value: 0x7F0A0069
			public const int sign_error_fail_certificate = 2131361897;
			
			// aapt resource value: 0x7F0A006A
			public const int sign_is_empty = 2131361898;
			
			// aapt resource value: 0x7F0A006B
			public const int sign_select_certificate = 2131361899;
			
			// aapt resource value: 0x7F0A006C
			public const int sign_title = 2131361900;
			
			// aapt resource value: 0x7F0A006D
			public const int simple_open_gl = 2131361901;
			
			// aapt resource value: 0x7F0A006E
			public const int single_page = 2131361902;
			
			// aapt resource value: 0x7F0A006F
			public const int squiggly = 2131361903;
			
			// aapt resource value: 0x7F0A0070
			public const int strikeout = 2131361904;
			
			// aapt resource value: 0x7F0A0071
			public const int tag_files = 2131361905;
			
			// aapt resource value: 0x7F0A0072
			public const int tag_navigate = 2131361906;
			
			// aapt resource value: 0x7F0A0073
			public const int tag_recent = 2131361907;
			
			// aapt resource value: 0x7F0A0074
			public const int text_cancel_label = 2131361908;
			
			// aapt resource value: 0x7F0A0075
			public const int thumbnail_creation_running = 2131361909;
			
			// aapt resource value: 0x7F0A0076
			public const int todo_3d = 2131361910;
			
			// aapt resource value: 0x7F0A0077
			public const int todo_attachment = 2131361911;
			
			// aapt resource value: 0x7F0A0078
			public const int todo_java_script = 2131361912;
			
			// aapt resource value: 0x7F0A0079
			public const int todo_open_url = 2131361913;
			
			// aapt resource value: 0x7F0A007A
			public const int todo_play_movie = 2131361914;
			
			// aapt resource value: 0x7F0A007B
			public const int todo_play_sound = 2131361915;
			
			// aapt resource value: 0x7F0A007C
			public const int txt_files_title = 2131361916;
			
			// aapt resource value: 0x7F0A007D
			public const int txt_no_files = 2131361917;
			
			// aapt resource value: 0x7F0A007E
			public const int txt_no_recent = 2131361918;
			
			// aapt resource value: 0x7F0A007F
			public const int underline = 2131361919;
			
			// aapt resource value: 0x7F0A0080
			public const int using_RGB_4444 = 2131361920;
			
			// aapt resource value: 0x7F0A0081
			public const int using_RGB_565 = 2131361921;
			
			// aapt resource value: 0x7F0A0082
			public const int vertical = 2131361922;
			
			// aapt resource value: 0x7F0A0083
			public const int view_pager = 2131361923;
			
			// aapt resource value: 0x7F0A0084
			public const int warning = 2131361924;
			
			// aapt resource value: 0x7F0A0085
			public const int yes = 2131361925;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7F0B0000
			public const int AppBaseTheme = 2131427328;
			
			// aapt resource value: 0x7F0B0001
			public const int AppTheme_NoTitleBar = 2131427329;
			
			// aapt resource value: 0x7F0B0003
			public const int popup_anim = 2131427331;
			
			// aapt resource value: 0x7F0B0002
			public const int ProgressBar = 2131427330;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			// aapt resource value: { 0x7F020000,0x7F020001,0x7F020002,0x7F020003,0x7F020004 }
			public static int[] SignaturePad = new int[] {
					2130837504,
					2130837505,
					2130837506,
					2130837507,
					2130837508};
			
			// aapt resource value: 0
			public const int SignaturePad_clearOnDoubleClick = 0;
			
			// aapt resource value: 1
			public const int SignaturePad_penColor = 1;
			
			// aapt resource value: 2
			public const int SignaturePad_penMaxWidth = 2;
			
			// aapt resource value: 3
			public const int SignaturePad_penMinWidth = 3;
			
			// aapt resource value: 4
			public const int SignaturePad_velocityFilterWeight = 4;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
