#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("RadaeePDFDemo.Resource", IsApplication=true)]

namespace RadaeePDFDemo
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int bar_back = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int btn_annot_ellipse = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int btn_annot_ink = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int btn_annot_line = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int btn_annot_note = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int btn_annot_rect = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int btn_back = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int btn_cancel = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int btn_done = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int btn_ink = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int btn_left = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int btn_outline = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int btn_perform = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int btn_print = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int btn_redo = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int btn_remove = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int btn_right = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int btn_search = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int btn_select = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int btn_undo = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int btn_view = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int btn_view_dual = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int btn_view_single = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int btn_view_vert = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int file03 = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int folder0 = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int folder1 = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int folder2 = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int ic_add = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public const int ic_bookmarks = 2130837533;
			
			// aapt resource value: 0x7f02001e
			public const int ic_more = 2130837534;
			
			// aapt resource value: 0x7f02001f
			public const int Icon = 2130837535;
			
			// aapt resource value: 0x7f020020
			public const int menu_back = 2130837536;
			
			// aapt resource value: 0x7f020021
			public const int pdf_custom_stamp = 2130837537;
			
			// aapt resource value: 0x7f020022
			public const int pt_end = 2130837538;
			
			// aapt resource value: 0x7f020023
			public const int pt_start = 2130837539;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f07002a
			public const int activate = 2131165226;
			
			// aapt resource value: 0x7f070037
			public const int add_bookmark = 2131165239;
			
			// aapt resource value: 0x7f070038
			public const int add_bookmark_icon = 2131165240;
			
			// aapt resource value: 0x7f070034
			public const int annot_combo = 2131165236;
			
			// aapt resource value: 0x7f070036
			public const int annot_text = 2131165238;
			
			// aapt resource value: 0x7f07000c
			public const int btn_annot = 2131165196;
			
			// aapt resource value: 0x7f070008
			public const int btn_annot_ink = 2131165192;
			
			// aapt resource value: 0x7f070005
			public const int btn_annot_line = 2131165189;
			
			// aapt resource value: 0x7f070009
			public const int btn_annot_note = 2131165193;
			
			// aapt resource value: 0x7f070007
			public const int btn_annot_oval = 2131165191;
			
			// aapt resource value: 0x7f070004
			public const int btn_annot_rect = 2131165188;
			
			// aapt resource value: 0x7f070006
			public const int btn_annot_stamp = 2131165190;
			
			// aapt resource value: 0x7f070000
			public const int btn_back = 2131165184;
			
			// aapt resource value: 0x7f070001
			public const int btn_edit = 2131165185;
			
			// aapt resource value: 0x7f07000b
			public const int btn_find = 2131165195;
			
			// aapt resource value: 0x7f070029
			public const int btn_goto = 2131165225;
			
			// aapt resource value: 0x7f070013
			public const int btn_left = 2131165203;
			
			// aapt resource value: 0x7f070011
			public const int btn_more = 2131165201;
			
			// aapt resource value: 0x7f07000e
			public const int btn_outline = 2131165198;
			
			// aapt resource value: 0x7f070002
			public const int btn_perform = 2131165186;
			
			// aapt resource value: 0x7f070010
			public const int btn_redo = 2131165200;
			
			// aapt resource value: 0x7f070003
			public const int btn_remove = 2131165187;
			
			// aapt resource value: 0x7f070012
			public const int btn_right = 2131165202;
			
			// aapt resource value: 0x7f07000d
			public const int btn_select = 2131165197;
			
			// aapt resource value: 0x7f07000f
			public const int btn_undo = 2131165199;
			
			// aapt resource value: 0x7f07000a
			public const int btn_view = 2131165194;
			
			// aapt resource value: 0x7f070021
			public const int chk_show = 2131165217;
			
			// aapt resource value: 0x7f07002e
			public const int curl_view = 2131165230;
			
			// aapt resource value: 0x7f070017
			public const int delete = 2131165207;
			
			// aapt resource value: 0x7f07001f
			public const int dlg_input = 2131165215;
			
			// aapt resource value: 0x7f070019
			public const int dlg_show_note = 2131165209;
			
			// aapt resource value: 0x7f07003e
			public const int imageView1 = 2131165246;
			
			// aapt resource value: 0x7f070040
			public const int imageView2 = 2131165248;
			
			// aapt resource value: 0x7f070042
			public const int imageView3 = 2131165250;
			
			// aapt resource value: 0x7f07001c
			public const int lab_content = 2131165212;
			
			// aapt resource value: 0x7f070016
			public const int lab_page = 2131165206;
			
			// aapt resource value: 0x7f07001a
			public const int lab_subj = 2131165210;
			
			// aapt resource value: 0x7f070018
			public const int label = 2131165208;
			
			// aapt resource value: 0x7f070035
			public const int lay_root = 2131165237;
			
			// aapt resource value: 0x7f07001e
			public const int lst_outline = 2131165214;
			
			// aapt resource value: 0x7f07002b
			public const int open = 2131165227;
			
			// aapt resource value: 0x7f07002d
			public const int open_assets = 2131165229;
			
			// aapt resource value: 0x7f07002c
			public const int open_http = 2131165228;
			
			// aapt resource value: 0x7f070033
			public const int pdf_nav = 2131165235;
			
			// aapt resource value: 0x7f07002f
			public const int pdf_pager = 2131165231;
			
			// aapt resource value: 0x7f070030
			public const int pdf_view = 2131165232;
			
			// aapt resource value: 0x7f07003b
			public const int print = 2131165243;
			
			// aapt resource value: 0x7f07003c
			public const int print_icon = 2131165244;
			
			// aapt resource value: 0x7f070031
			public const int progress = 2131165233;
			
			// aapt resource value: 0x7f070023
			public const int rad_copy = 2131165219;
			
			// aapt resource value: 0x7f070022
			public const int rad_group = 2131165218;
			
			// aapt resource value: 0x7f070024
			public const int rad_highlight = 2131165220;
			
			// aapt resource value: 0x7f070027
			public const int rad_squiggly = 2131165223;
			
			// aapt resource value: 0x7f070026
			public const int rad_strikeout = 2131165222;
			
			// aapt resource value: 0x7f070025
			public const int rad_underline = 2131165221;
			
			// aapt resource value: 0x7f070015
			public const int seek_page = 2131165205;
			
			// aapt resource value: 0x7f070039
			public const int show_bookmarks = 2131165241;
			
			// aapt resource value: 0x7f07003a
			public const int show_bookmarks_icon = 2131165242;
			
			// aapt resource value: 0x7f070043
			public const int thumb_view = 2131165251;
			
			// aapt resource value: 0x7f07001d
			public const int txt_content = 2131165213;
			
			// aapt resource value: 0x7f070014
			public const int txt_find = 2131165204;
			
			// aapt resource value: 0x7f070028
			public const int txt_name = 2131165224;
			
			// aapt resource value: 0x7f070020
			public const int txt_password = 2131165216;
			
			// aapt resource value: 0x7f070032
			public const int txt_path = 2131165234;
			
			// aapt resource value: 0x7f07001b
			public const int txt_subj = 2131165211;
			
			// aapt resource value: 0x7f070041
			public const int view_dual = 2131165249;
			
			// aapt resource value: 0x7f07003f
			public const int view_single = 2131165247;
			
			// aapt resource value: 0x7f07003d
			public const int view_vert = 2131165245;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int bar_act = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int bar_annot = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int bar_cmd = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int bar_find = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int bar_seek = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int bookmark_popup_menu = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int bookmark_row = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int dlg_note = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int dlg_outline = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int dlg_pswd = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int dlg_text = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int item_outline = 2130903051;
			
			// aapt resource value: 0x7f03000c
			public const int Main = 2130903052;
			
			// aapt resource value: 0x7f03000d
			public const int pdf_curl = 2130903053;
			
			// aapt resource value: 0x7f03000e
			public const int pdf_fragment = 2130903054;
			
			// aapt resource value: 0x7f03000f
			public const int pdf_layout = 2130903055;
			
			// aapt resource value: 0x7f030010
			public const int pdf_nav = 2130903056;
			
			// aapt resource value: 0x7f030011
			public const int pop_combo = 2130903057;
			
			// aapt resource value: 0x7f030012
			public const int pop_edit = 2130903058;
			
			// aapt resource value: 0x7f030013
			public const int pop_more = 2130903059;
			
			// aapt resource value: 0x7f030014
			public const int pop_view = 2130903060;
			
			// aapt resource value: 0x7f030015
			public const int thumb_view = 2130903061;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Raw
		{
			
			// aapt resource value: 0x7f040000
			public const int amiri_regular = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int arimo = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int arimob = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int arimobi = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int arimoi = 2130968580;
			
			// aapt resource value: 0x7f040005
			public const int cmaps = 2130968581;
			
			// aapt resource value: 0x7f040006
			public const int cmyk_rgb = 2130968582;
			
			// aapt resource value: 0x7f040007
			public const int cousine = 2130968583;
			
			// aapt resource value: 0x7f040008
			public const int cousineb = 2130968584;
			
			// aapt resource value: 0x7f040009
			public const int cousinebi = 2130968585;
			
			// aapt resource value: 0x7f04000a
			public const int cousinei = 2130968586;
			
			// aapt resource value: 0x7f04000b
			public const int rdf013 = 2130968587;
			
			// aapt resource value: 0x7f04000c
			public const int symbol = 2130968588;
			
			// aapt resource value: 0x7f04000d
			public const int tinos = 2130968589;
			
			// aapt resource value: 0x7f04000e
			public const int tinosb = 2130968590;
			
			// aapt resource value: 0x7f04000f
			public const int tinosbi = 2130968591;
			
			// aapt resource value: 0x7f040010
			public const int tinosi = 2130968592;
			
			// aapt resource value: 0x7f040011
			public const int umaps = 2130968593;
			
			static Raw()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Raw()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f05004a
			public const int ApplicationName = 2131034186;
			
			// aapt resource value: 0x7f050049
			public const int Hello = 2131034185;
			
			// aapt resource value: 0x7f050000
			public const int about = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int advance = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int annotation_failed = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int app_name = 2131034115;
			
			// aapt resource value: 0x7f05003d
			public const int bookmark_add = 2131034173;
			
			// aapt resource value: 0x7f05003e
			public const int bookmark_already_added = 2131034174;
			
			// aapt resource value: 0x7f05003f
			public const int bookmark_error = 2131034175;
			
			// aapt resource value: 0x7f050040
			public const int bookmark_label = 2131034176;
			
			// aapt resource value: 0x7f050041
			public const int bookmark_remove_error = 2131034177;
			
			// aapt resource value: 0x7f050042
			public const int bookmark_show = 2131034178;
			
			// aapt resource value: 0x7f050043
			public const int bookmark_success = 2131034179;
			
			// aapt resource value: 0x7f050044
			public const int bookmarks = 2131034180;
			
			// aapt resource value: 0x7f050004
			public const int browse_open_file = 2131034116;
			
			// aapt resource value: 0x7f050005
			public const int cancel = 2131034117;
			
			// aapt resource value: 0x7f050006
			public const int cannot_write_or_encrypted = 2131034118;
			
			// aapt resource value: 0x7f050007
			public const int catalog_not_found = 2131034119;
			
			// aapt resource value: 0x7f050008
			public const int copy_text = 2131034120;
			
			// aapt resource value: 0x7f050009
			public const int copy_text_to_clipboard = 2131034121;
			
			// aapt resource value: 0x7f05000a
			public const int create_pdf = 2131034122;
			
			// aapt resource value: 0x7f05000b
			public const int curl_pages = 2131034123;
			
			// aapt resource value: 0x7f050045
			public const int delete = 2131034181;
			
			// aapt resource value: 0x7f05000c
			public const int dual_page = 2131034124;
			
			// aapt resource value: 0x7f05000d
			public const int edit_catalog_failed = 2131034125;
			
			// aapt resource value: 0x7f05000e
			public const int exiting = 2131034126;
			
			// aapt resource value: 0x7f05000f
			public const int failed_encryption = 2131034127;
			
			// aapt resource value: 0x7f050010
			public const int failed_invalid_format = 2131034128;
			
			// aapt resource value: 0x7f050011
			public const int failed_invalid_password = 2131034129;
			
			// aapt resource value: 0x7f050012
			public const int failed_invalid_path = 2131034130;
			
			// aapt resource value: 0x7f050013
			public const int failed_unknown = 2131034131;
			
			// aapt resource value: 0x7f050014
			public const int file_not_exist = 2131034132;
			
			// aapt resource value: 0x7f050015
			public const int file_not_exist_error = 2131034133;
			
			// aapt resource value: 0x7f050016
			public const int file_not_opened = 2131034134;
			
			// aapt resource value: 0x7f050017
			public const int highlight_texts = 2131034135;
			
			// aapt resource value: 0x7f050018
			public const int input_password = 2131034136;
			
			// aapt resource value: 0x7f050019
			public const int javascript = 2131034137;
			
			// aapt resource value: 0x7f050046
			public const int loading = 2131034182;
			
			// aapt resource value: 0x7f05001a
			public const int loading_pdf = 2131034138;
			
			// aapt resource value: 0x7f05001b
			public const int no = 2131034139;
			
			// aapt resource value: 0x7f050047
			public const int no_bookmarks = 2131034183;
			
			// aapt resource value: 0x7f05001c
			public const int no_more_found = 2131034140;
			
			// aapt resource value: 0x7f05001d
			public const int no_more_redo = 2131034141;
			
			// aapt resource value: 0x7f05001e
			public const int no_more_undo = 2131034142;
			
			// aapt resource value: 0x7f05001f
			public const int no_pdf_outlines = 2131034143;
			
			// aapt resource value: 0x7f050020
			public const int note_content = 2131034144;
			
			// aapt resource value: 0x7f050021
			public const int ok = 2131034145;
			
			// aapt resource value: 0x7f050022
			public const int open_asset = 2131034146;
			
			// aapt resource value: 0x7f050023
			public const int open_http = 2131034147;
			
			// aapt resource value: 0x7f050024
			public const int open_sdcard = 2131034148;
			
			// aapt resource value: 0x7f050025
			public const int page_change_block = 2131034149;
			
			// aapt resource value: 0x7f050026
			public const int pdf_outline = 2131034150;
			
			// aapt resource value: 0x7f050027
			public const int pdf_print_calculation_failed = 2131034151;
			
			// aapt resource value: 0x7f050028
			public const int pdf_print_not_available = 2131034152;
			
			// aapt resource value: 0x7f050029
			public const int please_wait = 2131034153;
			
			// aapt resource value: 0x7f050048
			public const int print = 2131034184;
			
			// aapt resource value: 0x7f05002a
			public const int process_selected_text = 2131034154;
			
			// aapt resource value: 0x7f05002b
			public const int save_msg = 2131034155;
			
			// aapt resource value: 0x7f05002c
			public const int simple_open_gl = 2131034156;
			
			// aapt resource value: 0x7f05002d
			public const int single_page = 2131034157;
			
			// aapt resource value: 0x7f05002e
			public const int squiggly = 2131034158;
			
			// aapt resource value: 0x7f05002f
			public const int strikeout = 2131034159;
			
			// aapt resource value: 0x7f050030
			public const int thumbnail_creation_running = 2131034160;
			
			// aapt resource value: 0x7f050031
			public const int todo_3d = 2131034161;
			
			// aapt resource value: 0x7f050032
			public const int todo_attachment = 2131034162;
			
			// aapt resource value: 0x7f050033
			public const int todo_java_script = 2131034163;
			
			// aapt resource value: 0x7f050034
			public const int todo_open_url = 2131034164;
			
			// aapt resource value: 0x7f050035
			public const int todo_play_movie = 2131034165;
			
			// aapt resource value: 0x7f050036
			public const int todo_play_sound = 2131034166;
			
			// aapt resource value: 0x7f050037
			public const int underline = 2131034167;
			
			// aapt resource value: 0x7f050038
			public const int using_RGB_4444 = 2131034168;
			
			// aapt resource value: 0x7f050039
			public const int using_RGB_565 = 2131034169;
			
			// aapt resource value: 0x7f05003a
			public const int vertical = 2131034170;
			
			// aapt resource value: 0x7f05003b
			public const int view_pager = 2131034171;
			
			// aapt resource value: 0x7f05003c
			public const int yes = 2131034172;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060000
			public const int AppBaseTheme = 2131099648;
			
			// aapt resource value: 0x7f060002
			public const int AppTheme = 2131099650;
			
			// aapt resource value: 0x7f060001
			public const int ProgressBar = 2131099649;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
